-- ACE Discover Storage setup now lives in the versioned migration:
-- supabase/migrations/202608200001_profile_image_storage.sql
--
-- Apply that complete migration instead of running a partial bucket-only setup.
-- It configures the profile-images bucket, its scoped public-read policy, the
-- canonical dataset_profiles.storage_image_path field, and the narrow
-- service-role RPC used by the rerunnable migration tool.
